title: BabyAGI
email: 
description: >-
  BabyAGI is an AI-powered task management system that uses OpenAI and Pinecone APIs to create, prioritize, and execute tasks.
baseurl: ""
url: "https://babyagi.org"
twitter_username: yoheinakajima
github_username:  yoheinakajima
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
